### ISSUE TITLE
Snow units in ERA5/-Land variables

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/miranda#106]
I've run into some confusion in the units-handling for the converted snow variables (`snd`, `snr`, `snw`). I want to be certain that the conversions are being performed properly.

## ERA5 and ERA5-Prelimary-Back-Extension
- `rsn`: Snow Density (kg m-3) → `snr`: `surface_snow_density`  (kg m-3)
- `sd`: Snow Depth (m of water equivalent; corrected to Mg m-2) → `snw`: `surface_snow_amount` Snow thickness in m of liquid water equivalent converted to snow amount using a water density of 1000 kg/m³. (kg m-2)

## ERA5-Land
- `sde`: Snow Depth (m; not water equivalent) -> `snd`: `surface_snow_thickness` (m) 
- `snr`: Snow Density (kg m-3) → `snr`: `surface_snow_density` (kg m-3)
- `sd`: Snow Depth Water Equivalent (m of water equivalent; corrected to Mg m-2) → `snw`: `surface_snow_amount` "Snow thickness in m of liquid water equivalent converted to snow amount using a water density of 1000 kg/m³". (kg m-2)

There are currently no fucntions for calculating `snd` given `snr` and `snw`. This should be added. The relevant literature for all snow variables can be found here: https://www.ecmwf.int/sites/default/files/elibrary/2016/17117-part-iv-physical-processes.pdf#section.H.4

**Comment by aulemahal** [comment]
When you say "this should be added", are you thinking about `xclim` or `miranda`?

Some code exists in the MELCC parser I believe. Also, there I used `snow_density` as the variable name (since there are no CMIP6 standard), but I do like `snr`, its shorter and not conflicting with CMIP6. We could change the MELCC parser to be coherent.

As for the `swe <-> snw` transformations, the most recent xclim adds a few functionalities for that. At least, a `convert_units_to(swe, snw)` should work out-of-the-box if the correct standard name if set on the input.

**Comment by Zeitsperre** [comment]
This is good to know! I'm thinking that this conversion could be added here, but based on existing functions (xclim is a dependency in miranda).

Are the existing mapping for ERA5 to CF-like units correct for `swe` and `snw`? How can we be sure to make use of `snr` when converting them?

Having a consistent variable code for snow density is a good idea. `snr` does the job.

**Comment by Zeitsperre** [comment]
Fixed with #1271
